//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameOfLife.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zdroje {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zdroje() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameOfLife.Properties.zdroje", typeof(zdroje).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48,37;48,38;48,39;49,38;47,38;
        ///50,48;51,48;53,48;52,48;49,48;48,48;50,47;50,45;50,46;51,49;51,50;51,51;
        ///43,46;44,46;45,46;
        ///42,44;43,44;44,44;45,44;46,44;
        ///41,43;42,43;43,43;44,43;45,43;46,43;
        ///40,45;41,45;42,45;43,45;44,45;45,45;46,45;
        ///40,45;41,45;42,45;43,45;44,45;45,45;46,45;47,45;
        ///40,45;41,45;42,45;43,45;44,45;45,45;46,45;47,45;48,45;
        ///40,45;41,45;42,45;43,45;44,45;45,45;46,45;47,45;48,45;49,45;
        ///40,45;41,45;42,45;43,45;44,45;45,45;46,45;47,45;48,45;49,45;50,45;51,45;52,45;53,45;
        ///40,45;41,45;42,45;43,45;44,4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sablony {
            get {
                return ResourceManager.GetString("sablony", resourceCulture);
            }
        }
    }
}
